import { Link } from 'react-router-dom';
import { usePageTitle } from '@/hooks/usePageTitle';

const EFFECTIVE_DATE = 'February 19, 2026';

const sections = [
    {
        id: 'acceptance',
        title: '1. Acceptance of Terms',
        content: `By creating an account, accessing, or using KoreX System ("the Service"), operated by Kontrolly Consulting LLC ("the Company"), you agree to be legally bound by these Terms of Service ("Terms"). If you do not agree to ALL of these Terms, you must immediately cease using the Service. Your continued use of the Service following the posting of changes constitutes irrevocable acceptance of those changes.\n\nThese Terms constitute a legally binding agreement between you ("User," "you," or "your") and Kontrolly Consulting LLC, doing business as KoreX System ("KoreX," "the Company," "we," "us," or "our"). Kontrolly Consulting LLC is a limited liability company organized under the laws of the United States.`,
    },
    {
        id: 'description',
        title: '2. Service Description',
        content: `KoreX System is a proprietary financial management and analysis tool, owned and operated by Kontrolly Consulting LLC, that provides debt tracking, cashflow visualization, velocity banking projections, and strategic financial planning tools. The Service allows users to input their financial data and receive calculated projections based on proprietary mathematical models and algorithms.\n\nThe Service is provided on a subscription basis with different tiers of functionality as described on our pricing page.`,
    },
    {
        id: 'no-financial-advice',
        title: '3. No Financial Advice — Disclaimer',
        content: `THE SERVICE DOES NOT PROVIDE FINANCIAL, INVESTMENT, TAX, OR LEGAL ADVICE. ALL PROJECTIONS, RECOMMENDATIONS, CALCULATIONS, AND OUTPUTS GENERATED BY KOREX SYSTEM ARE FOR INFORMATIONAL AND EDUCATIONAL PURPOSES ONLY. They are mathematical models based on the data you provide and should not be construed as professional financial advice.\n\nYou expressly acknowledge and agree that:\n• All financial decisions are made at your own risk and discretion.\n• Projections are estimates and are NOT guarantees of future results.\n• You should consult a qualified financial advisor before making significant financial decisions.\n• Past performance projections do not guarantee future outcomes.\n• KoreX System assumes no responsibility whatsoever for financial losses, missed opportunities, or adverse outcomes resulting from the use of this Service.\n• The Velocity Banking strategy involves risk and is not suitable for all financial situations.\n• Interest calculations and payoff projections are approximations and may differ from actual bank calculations.\n• We do not guarantee the mathematical accuracy of any projection under all circumstances.`,
    },
    {
        id: 'disclaimer-warranties',
        title: '4. Disclaimer of Warranties',
        content: `THE SERVICE IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO:\n\n• IMPLIED WARRANTIES OF MERCHANTABILITY\n• FITNESS FOR A PARTICULAR PURPOSE\n• NON-INFRINGEMENT\n• ACCURACY OR RELIABILITY OF ANY INFORMATION OR CONTENT\n• UNINTERRUPTED OR ERROR-FREE OPERATION\n\nKoreX does not warrant that the Service will meet your specific requirements, that results obtained from the Service will be accurate or reliable, or that defects in the Service will be corrected.\n\nNo advice or information, whether oral or written, obtained by you from KoreX or through the Service shall create any warranty not expressly stated in these Terms.`,
    },
    {
        id: 'accounts',
        title: '5. Account Responsibilities',
        content: `You are responsible for:\n• Maintaining the confidentiality of your login credentials.\n• All activity that occurs under your account, whether or not authorized by you.\n• Providing accurate and truthful information.\n• Notifying us immediately of any unauthorized use of your account.\n• Ensuring your use complies with all applicable local, state, national, and international laws.\n\nWe reserve the right to suspend or terminate accounts that violate these Terms, are used for fraudulent purposes, or are suspected of any illegal activity.`,
    },
    {
        id: 'data-accuracy',
        title: '6. Data Accuracy',
        content: `KoreX System performs calculations based solely on data you provide. We do not independently verify the accuracy, completeness, or reliability of any financial data entered by users. The accuracy of projections and analyses depends entirely on the accuracy of the data you input.\n\nYou are solely responsible for ensuring that the financial information you enter (account balances, interest rates, income, expenses, payment schedules) is correct and up-to-date. KoreX shall not be held liable for any inaccurate projections or calculations resulting from incorrect user-provided data.`,
    },
    {
        id: 'intellectual-property',
        title: '7. Intellectual Property & Proprietary Rights',
        content: `COPYRIGHT NOTICE: © ${new Date().getFullYear()} Kontrolly Consulting LLC (DBA KoreX System). All Rights Reserved.\n\nAll content, software, algorithms, mathematical models, proprietary formulas, source code, object code, user interface designs, visual designs, logos, trademarks, trade names, service marks, and branding associated with KoreX System (collectively, "Proprietary Materials") are the exclusive intellectual property of Kontrolly Consulting LLC and are protected by:\n\n• United States and international copyright laws (including the Digital Millennium Copyright Act)\n• Trademark laws and registrations\n• Trade secret protections\n• Patent laws (including provisional and pending patent applications)\n• International intellectual property treaties and conventions\n\nPROHIBITED ACTIVITIES — You may NOT, without prior written authorization from Kontrolly Consulting LLC:\n• Copy, reproduce, duplicate, or replicate any part of the Service or its Proprietary Materials.\n• Reverse engineer, decompile, disassemble, or attempt to derive the source code of the Service.\n• Modify, adapt, translate, or create derivative works based on the Service.\n• Distribute, sublicense, lease, rent, loan, or transfer the Service to any third party.\n• Use any automated means (bots, scrapers, crawlers) to access or extract data from the Service.\n• Remove, alter, or obscure any copyright, trademark, or proprietary rights notices.\n• Use KoreX's name, logos, or branding without express written permission.\n\nThe Velocity Banking engine, cashflow projection algorithms, debt acceleration models, and Peace Shield™ methodology are proprietary technologies of Kontrolly Consulting LLC. Any unauthorized use, reproduction, or distribution constitutes a violation of intellectual property law and may result in civil and criminal penalties.`,
    },
    {
        id: 'third-party',
        title: '8. Third-Party Services',
        content: `The Service integrates with third-party providers including but not limited to:\n• **Google OAuth** — for authentication\n• **Supabase** — for data storage and authentication infrastructure\n• **LemonSqueezy** — for payment processing and subscription management\n\nWe are not responsible for the availability, security, privacy practices, or policies of these third-party services. Your use of these services is subject to their respective terms, conditions, and privacy policies. KoreX shall not be liable for any damages or losses arising from the use or unavailability of third-party services.`,
    },
    {
        id: 'limitation',
        title: '9. Limitation of Liability',
        content: `TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, KONTROLLY CONSULTING LLC (DBA KOREX SYSTEM), ITS FOUNDERS, MEMBERS, MANAGERS, OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, CONTRACTORS, AFFILIATES, LICENSORS, AND SUCCESSORS (COLLECTIVELY, "KOREX PARTIES") SHALL NOT BE LIABLE FOR:\n\n• Any direct, indirect, incidental, special, consequential, exemplary, or punitive damages of any kind.\n• Any loss of profits, revenue, data, goodwill, or financial losses.\n• Any damages arising from your reliance on projections, recommendations, or calculations provided by the Service.\n• Any damages resulting from unauthorized access to or alteration of your data.\n• Any interruption, suspension, or cessation of the Service.\n• Cost of procurement of substitute goods or services.\n• Any errors, inaccuracies, or omissions in any content.\n• Any personal injury or property damage resulting from your use of the Service.\n\nTHE TOTAL AGGREGATE LIABILITY OF THE KOREX PARTIES FOR ANY CLAIM ARISING OUT OF OR RELATING TO THESE TERMS OR THE SERVICE SHALL NOT EXCEED THE LESSER OF: (A) THE AMOUNT YOU HAVE ACTUALLY PAID TO KONTROLLY CONSULTING LLC IN THE TWELVE (12) MONTHS IMMEDIATELY PRECEDING THE CLAIM, OR (B) ONE HUNDRED U.S. DOLLARS ($100.00).\n\nTHIS LIMITATION APPLIES REGARDLESS OF THE THEORY OF LIABILITY (CONTRACT, TORT, STRICT LIABILITY, OR OTHERWISE), EVEN IF THE KOREX PARTIES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.\n\nYOU EXPRESSLY ACKNOWLEDGE AND AGREE THAT KONTROLLY CONSULTING LLC SHALL NOT BE LIABLE TO YOU FOR ANY DAMAGES RESULTING FROM YOUR USE OF THE SERVICE, INCLUDING BUT NOT LIMITED TO YOUR RELIANCE ON ANY INFORMATION OBTAINED FROM THE SERVICE.`,
    },
    {
        id: 'indemnification',
        title: '10. Indemnification',
        content: `You agree to fully indemnify, defend, and hold harmless Kontrolly Consulting LLC (DBA KoreX System), its founders, members, managers, affiliates, officers, directors, employees, contractors, agents, licensors, and successors (collectively, "Indemnified Parties") from and against any and all claims, liabilities, damages, losses, costs, and expenses (including but not limited to reasonable attorneys' fees, court costs, and expert witness fees) arising out of or in any way connected with:\n\n• Your access to or use of the Service.\n• Your violation of these Terms.\n• Your violation of any third-party rights, including intellectual property rights.\n• Any financial decisions, actions, or omissions you make based on information, projections, or recommendations provided by the Service.\n• Any content or data you submit, post, or transmit through the Service.\n• Any negligent or wrongful conduct by you.\n\nThis indemnification obligation shall survive the termination of your account and these Terms.`,
    },
    {
        id: 'arbitration',
        title: '11. Dispute Resolution & Arbitration',
        content: `PLEASE READ THIS SECTION CAREFULLY — IT AFFECTS YOUR LEGAL RIGHTS.\n\nAny dispute, claim, or controversy arising out of or relating to these Terms, the Service, or your relationship with Kontrolly Consulting LLC (DBA KoreX System) (collectively, "Disputes") shall be resolved through binding individual arbitration and NOT through court proceedings.\n\nARBITRATION RULES:\n• Arbitration shall be administered by the American Arbitration Association (AAA) under its Consumer Arbitration Rules.\n• The arbitration shall be conducted by a single neutral arbitrator.\n• The arbitration shall take place in the United States, and may be conducted remotely.\n• The arbitrator's decision shall be final and binding.\n\nCLASS ACTION WAIVER:\nYOU AND KONTROLLY CONSULTING LLC AGREE THAT EACH PARTY MAY BRING CLAIMS AGAINST THE OTHER ONLY IN YOUR INDIVIDUAL CAPACITY, AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS, COLLECTIVE, OR REPRESENTATIVE ACTION. The arbitrator may not consolidate more than one person's claims and may not otherwise preside over any form of class or representative proceeding.\n\nEXCEPTIONS — The following are exempt from arbitration:\n• Claims related to intellectual property infringement.\n• Claims eligible for small claims court.\n• Emergency injunctive relief to prevent irreparable harm.`,
    },
    {
        id: 'user-data',
        title: '12. User Data & Privacy',
        content: `Your use of the Service is also governed by our Privacy Policy, which is incorporated into these Terms by reference.\n\nYou retain ownership of the raw financial data you input into the Service. However, you grant KoreX a non-exclusive, worldwide, royalty-free license to use, process, and store your data solely for the purpose of providing and improving the Service.\n\nKoreX shall implement reasonable security measures to protect your data but cannot guarantee absolute security. You acknowledge that no method of electronic transmission or storage is 100% secure.`,
    },
    {
        id: 'termination',
        title: '13. Account Termination',
        content: `We reserve the right to suspend or terminate your account at our sole discretion, without prior notice or liability, for any reason including but not limited to:\n• Violation of these Terms.\n• Fraudulent, abusive, or illegal activity.\n• Extended period of inactivity.\n• Non-payment of subscription fees.\n• Conduct that is harmful to other users or the Service.\n\nUpon termination:\n• Your right to use the Service ceases immediately.\n• We may delete your data in accordance with our Privacy Policy.\n• All licenses granted to you under these Terms shall terminate.\n• Sections regarding Intellectual Property, Limitation of Liability, Indemnification, Arbitration, and Disclaimer of Warranties shall survive termination.`,
    },
    {
        id: 'modifications',
        title: '14. Changes to Terms',
        content: `We reserve the right to modify these Terms at any time at our sole discretion. Material changes will be communicated through the Service, via email, or by posting updated Terms on our website. Your continued use of the Service after changes are posted constitutes acceptance of the updated Terms.\n\nIf you do not agree with the modified Terms, your sole remedy is to discontinue use of the Service.\n\nWe encourage you to review these Terms periodically.`,
    },
    {
        id: 'governing-law',
        title: '15. Governing Law',
        content: `These Terms shall be governed by and construed in accordance with the laws of the United States of America, without regard to conflict of law principles. To the extent that arbitration does not apply, any disputes arising under these Terms shall be resolved in the federal or state courts located within the United States, and you consent to the personal jurisdiction of such courts.`,
    },
    {
        id: 'severability',
        title: '16. Severability & Waiver',
        content: `If any provision of these Terms is found to be unlawful, void, or unenforceable, that provision shall be deemed severable and shall not affect the validity and enforceability of the remaining provisions.\n\nThe failure of KoreX to exercise or enforce any right or provision of these Terms shall not constitute a waiver of such right or provision. Any waiver must be made in writing to be effective.`,
    },
    {
        id: 'entire-agreement',
        title: '17. Entire Agreement',
        content: `These Terms, together with the Privacy Policy and any subscription agreements, constitute the entire agreement between you and KoreX regarding the Service. These Terms supersede all prior or contemporaneous communications, proposals, and agreements, whether oral or written, between you and KoreX regarding the Service.`,
    },
    {
        id: 'contact',
        title: '18. Contact',
        content: `If you have questions about these Terms, please contact us through the Service's support channels or at the email provided in your account settings.\n\n© ${new Date().getFullYear()} Kontrolly Consulting LLC. All Rights Reserved.\nKoreX™, KoreX System™, Peace Shield™, and the KoreX logo are trademarks of Kontrolly Consulting LLC.\nAll proprietary algorithms, methodologies, and technologies are the exclusive property of Kontrolly Consulting LLC.`,
    },
];

export default function TermsOfServicePage() {
    usePageTitle('Terms of Service');
    return (
        <div className="min-h-screen bg-slate-950 text-slate-300">
            {/* Header */}
            <div className="sticky top-0 z-20 bg-slate-950/90 backdrop-blur-xl border-b border-white/5">
                <div className="max-w-4xl mx-auto px-6 py-4 flex items-center justify-between">
                    <Link to="/login" className="flex items-center gap-2 text-sm text-slate-400 hover:text-white transition-colors">
                        <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="2">
                            <path strokeLinecap="round" strokeLinejoin="round" d="M15 19l-7-7 7-7" />
                        </svg>
                        Back to Login
                    </Link>
                    <div className="flex items-center gap-2">
                        <img src="/korex-icon.png" alt="KoreX" className="w-6 h-6" />
                        <span className="text-sm font-semibold text-white">KoreX</span>
                    </div>
                </div>
            </div>

            {/* Content */}
            <div className="max-w-4xl mx-auto px-6 py-12">
                <div className="mb-10">
                    <h1 className="text-3xl font-bold text-white mb-2">Terms of Service</h1>
                    <p className="text-sm text-slate-500">Effective Date: {EFFECTIVE_DATE}</p>
                </div>

                {/* Quick Nav */}
                <div className="mb-10 p-4 rounded-xl bg-slate-900/50 border border-white/5">
                    <p className="text-xs uppercase tracking-wider text-slate-500 mb-3 font-medium">Table of Contents</p>
                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-1">
                        {sections.map((s) => (
                            <a
                                key={s.id}
                                href={`#${s.id}`}
                                className="text-sm text-amber-400/70 hover:text-amber-400 transition-colors py-1"
                            >
                                {s.title}
                            </a>
                        ))}
                    </div>
                </div>

                {/* Sections */}
                <div className="space-y-10">
                    {sections.map((s) => (
                        <section key={s.id} id={s.id} className="scroll-mt-20">
                            <h2 className="text-lg font-semibold text-white mb-3">{s.title}</h2>
                            <div className="text-sm leading-relaxed whitespace-pre-line text-slate-400">
                                {s.content.split('**').map((part, i) =>
                                    i % 2 === 1 ? (
                                        <strong key={i} className="text-slate-200">{part}</strong>
                                    ) : (
                                        <span key={i}>{part}</span>
                                    )
                                )}
                            </div>
                        </section>
                    ))}
                </div>

                {/* Footer */}
                <div className="mt-16 pt-8 border-t border-white/5 text-center">
                    <p className="text-xs text-slate-600">
                        KoreX Financial System — &copy; {new Date().getFullYear()} Kontrolly Consulting LLC. All rights reserved.
                    </p>
                    <div className="flex items-center justify-center gap-4 mt-3">
                        <Link to="/privacy" className="text-xs text-amber-400/60 hover:text-amber-400 transition-colors">Privacy Policy</Link>
                        <span className="text-slate-700">•</span>
                        <Link to="/login" className="text-xs text-amber-400/60 hover:text-amber-400 transition-colors">Back to Login</Link>
                    </div>
                </div>
            </div>
        </div>
    );
}
