import { Link } from 'react-router-dom';

const EFFECTIVE_DATE = 'February 14, 2026';

const sections = [
    {
        id: 'acceptance',
        title: '1. Acceptance of Terms',
        content: `By creating an account or using CoreX System ("the Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to all of these Terms, do not use the Service. Your continued use of the Service following the posting of changes constitutes acceptance of those changes.`,
    },
    {
        id: 'description',
        title: '2. Service Description',
        content: `CoreX System is a financial management and analysis tool that provides debt tracking, cashflow visualization, and velocity banking projections. The Service allows users to input their financial data and receive calculated projections based on mathematical models.`,
    },
    {
        id: 'no-financial-advice',
        title: '3. No Financial Advice',
        content: `THE SERVICE DOES NOT PROVIDE FINANCIAL, INVESTMENT, TAX, OR LEGAL ADVICE. All projections, recommendations, calculations, and outputs generated by CoreX System are for informational and educational purposes only. They are mathematical models based on the data you provide and should not be construed as professional financial advice.\n\nYou acknowledge that:\n• All financial decisions are made at your own risk and discretion.\n• Projections are estimates and are NOT guarantees of future results.\n• You should consult a qualified financial advisor before making significant financial decisions.\n• Past performance projections do not guarantee future outcomes.\n• CoreX System assumes no responsibility for financial losses or missed opportunities resulting from the use of this Service.`,
    },
    {
        id: 'accounts',
        title: '4. Account Responsibilities',
        content: `You are responsible for:\n• Maintaining the confidentiality of your login credentials.\n• All activity that occurs under your account.\n• Providing accurate and truthful information.\n• Notifying us immediately of any unauthorized use of your account.\n\nWe reserve the right to suspend or terminate accounts that violate these Terms or are used for fraudulent purposes.`,
    },
    {
        id: 'data-accuracy',
        title: '5. Data Accuracy',
        content: `CoreX System performs calculations based on data you provide. We do not independently verify the accuracy, completeness, or reliability of any financial data entered by users. The accuracy of projections and analyses depends entirely on the accuracy of the data you input.\n\nYou are solely responsible for ensuring that the financial information you enter (account balances, interest rates, income, expenses) is correct and up-to-date.`,
    },
    {
        id: 'third-party',
        title: '6. Third-Party Services',
        content: `The Service integrates with third-party providers including but not limited to:\n• **Google OAuth** — for authentication\n• **Supabase** — for data storage and authentication infrastructure\n\nWe are not responsible for the availability, security, or privacy practices of these third-party services. Your use of these services is subject to their respective terms and privacy policies.`,
    },
    {
        id: 'intellectual-property',
        title: '7. Intellectual Property',
        content: `All content, algorithms, designs, code, trademarks, and branding associated with CoreX System are the intellectual property of CoreX and are protected by applicable copyright and trademark laws. You may not reproduce, distribute, modify, or create derivative works from any part of the Service without prior written consent.`,
    },
    {
        id: 'limitation',
        title: '8. Limitation of Liability',
        content: `TO THE MAXIMUM EXTENT PERMITTED BY LAW, COREX SYSTEM AND ITS CREATORS, OFFICERS, EMPLOYEES, AND AGENTS SHALL NOT BE LIABLE FOR:\n\n• Any indirect, incidental, special, consequential, or punitive damages.\n• Any loss of profits, revenue, data, or financial losses.\n• Any damages arising from your reliance on projections or recommendations provided by the Service.\n• Any damages resulting from unauthorized access to or alteration of your data.\n• Any interruption or cessation of the Service.\n\nOur total liability for any claim arising out of or relating to these Terms or the Service shall not exceed the amount you have paid us in the twelve (12) months preceding the claim, or $100, whichever is less.`,
    },
    {
        id: 'indemnification',
        title: '9. Indemnification',
        content: `You agree to indemnify, defend, and hold harmless CoreX System, its creators, affiliates, and agents from and against any claims, liabilities, damages, losses, and expenses (including reasonable attorneys' fees) arising out of or in any way connected with:\n• Your use of the Service.\n• Your violation of these Terms.\n• Your violation of any third-party rights.\n• Any financial decisions you make based on information provided by the Service.`,
    },
    {
        id: 'termination',
        title: '10. Account Termination',
        content: `We reserve the right to suspend or terminate your account at our sole discretion, without prior notice, for any reason including but not limited to:\n• Violation of these Terms.\n• Fraudulent or illegal activity.\n• Extended period of inactivity.\n\nUpon termination, your right to use the Service ceases immediately. We may delete your data in accordance with our Privacy Policy.`,
    },
    {
        id: 'modifications',
        title: '11. Changes to Terms',
        content: `We reserve the right to modify these Terms at any time. Material changes will be communicated through the Service or via email. Your continued use of the Service after changes are posted constitutes acceptance of the updated Terms.\n\nWe encourage you to review these Terms periodically.`,
    },
    {
        id: 'governing-law',
        title: '12. Governing Law',
        content: `These Terms shall be governed by and construed in accordance with the laws of the United States, without regard to conflict of law principles. Any disputes arising under these Terms shall be resolved in the appropriate courts within the United States.`,
    },
    {
        id: 'contact',
        title: '13. Contact',
        content: `If you have questions about these Terms, please contact us through the Service's support channels or at the email provided in your account settings.`,
    },
];

export default function TermsOfServicePage() {
    return (
        <div className="min-h-screen bg-slate-950 text-slate-300">
            {/* Header */}
            <div className="sticky top-0 z-20 bg-slate-950/90 backdrop-blur-xl border-b border-white/5">
                <div className="max-w-4xl mx-auto px-6 py-4 flex items-center justify-between">
                    <Link to="/login" className="flex items-center gap-2 text-sm text-slate-400 hover:text-white transition-colors">
                        <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="2">
                            <path strokeLinecap="round" strokeLinejoin="round" d="M15 19l-7-7 7-7" />
                        </svg>
                        Back to Login
                    </Link>
                    <div className="flex items-center gap-2">
                        <div className="w-6 h-6 rounded-md bg-gradient-to-br from-amber-400 to-amber-600 flex items-center justify-center">
                            <svg viewBox="0 0 24 24" fill="none" className="w-3.5 h-3.5 text-white">
                                <path d="M12 2L3 7v10l9 5 9-5V7l-9-5z" stroke="currentColor" strokeWidth="2" />
                            </svg>
                        </div>
                        <span className="text-sm font-semibold text-white">CoreX</span>
                    </div>
                </div>
            </div>

            {/* Content */}
            <div className="max-w-4xl mx-auto px-6 py-12">
                <div className="mb-10">
                    <h1 className="text-3xl font-bold text-white mb-2">Terms of Service</h1>
                    <p className="text-sm text-slate-500">Effective Date: {EFFECTIVE_DATE}</p>
                </div>

                {/* Quick Nav */}
                <div className="mb-10 p-4 rounded-xl bg-slate-900/50 border border-white/5">
                    <p className="text-xs uppercase tracking-wider text-slate-500 mb-3 font-medium">Table of Contents</p>
                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-1">
                        {sections.map((s) => (
                            <a
                                key={s.id}
                                href={`#${s.id}`}
                                className="text-sm text-amber-400/70 hover:text-amber-400 transition-colors py-1"
                            >
                                {s.title}
                            </a>
                        ))}
                    </div>
                </div>

                {/* Sections */}
                <div className="space-y-10">
                    {sections.map((s) => (
                        <section key={s.id} id={s.id} className="scroll-mt-20">
                            <h2 className="text-lg font-semibold text-white mb-3">{s.title}</h2>
                            <div className="text-sm leading-relaxed whitespace-pre-line text-slate-400">
                                {s.content.split('**').map((part, i) =>
                                    i % 2 === 1 ? (
                                        <strong key={i} className="text-slate-200">{part}</strong>
                                    ) : (
                                        <span key={i}>{part}</span>
                                    )
                                )}
                            </div>
                        </section>
                    ))}
                </div>

                {/* Footer */}
                <div className="mt-16 pt-8 border-t border-white/5 text-center">
                    <p className="text-xs text-slate-600">
                        CoreX Financial System — &copy; {new Date().getFullYear()} All rights reserved.
                    </p>
                    <div className="flex items-center justify-center gap-4 mt-3">
                        <Link to="/privacy" className="text-xs text-amber-400/60 hover:text-amber-400 transition-colors">Privacy Policy</Link>
                        <span className="text-slate-700">•</span>
                        <Link to="/login" className="text-xs text-amber-400/60 hover:text-amber-400 transition-colors">Back to Login</Link>
                    </div>
                </div>
            </div>
        </div>
    );
}
